#!/bin/sh -e

case "$1" in
    configure)
        echo "Enable SMART if disabled"
        for hdd in $(ls /dev/ | egrep ^[hs]{1}d[a-z]{1}$); do
            if [ "$(smartctl -i /dev/${hdd} | grep Disabled | wc -l)" -gt "0" ]; then
                smartctl -s on -q silent /dev/${hdd}
                echo "  - Enabled SMART on ${hdd}"
            fi
        done

        if command -v systemctl >/dev/null 2>&1; then
            deb-systemd-invoke restart zabbix-agent || true
        elif command -v invoke-rc.d >/dev/null 2>&1; then
            invoke-rc.d zabbix-agent stop || true
            invoke-rc.d zabbix-agent start || true
        else
            /etc/init.d/zabbix-agent stop || true
            /etc/init.d/zabbix-agent start || true
        fi
    ;;
    abort-upgrade|abort-deconfigure|abort-remove)
    ;;
    *)
        echo "$0 called with unknown argument \`$1'" 1>&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
