#!/bin/sh -e

case "$1" in
    purge|remove)
        if command -v systemctl >/dev/null 2>&1; then
            deb-systemd-invoke restart zabbix-agent || true
        elif command -v invoke-rc.d >/dev/null 2>&1; then
            invoke-rc.d zabbix-agent stop || true
            invoke-rc.d zabbix-agent start || true
        else
            /etc/init.d/zabbix-agent stop || true
            /etc/init.d/zabbix-agent start || true
        fi
    ;;
    failed-upgrade|abort-install|abort-upgrade|disappear|upgrade)
    ;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
